Fix dropdown menu button label issue
lorenzolewis/starlight-utils pull request #105
Opened 2024-10-03 03:07 UTC by huijing

Fixes https://github.com/lorenzolewis/starlight-utils/issues/104
Replaces `` with `{Astro.locals.t("menuButton.accessibleLabel")}`

2024-10-04 07:05 UTC, lorenzolewis commented
Thank you for this! I believe we will also need to bump the minimum version of Starlight in package.json for the version in which this change occurred. Will you be able to do that as well as add a changeset to this PR? This would be a "minor" change to reflect Starlight's versioning. 

Let me know if you need any help with that and thank you!

2024-10-04 08:16 UTC, huijing commented
I ran `npx changeset` and added the changeset, however, I'm not sure if I did the package.json bump correctly. The Starlight version with the change was 0.28.0 which requires the Astro version to be 4.14.0 (https://github.com/withastro/starlight/releases/tag/%40astrojs%2Fstarlight%400.28.0), so I changed that too. But again, not sure if that's how it's supposed to work.

2024-10-04 14:35 UTC, lorenzolewis requested changes
Thanks! A few quick changes and then it should be good to go!

2024-10-04 14:35 UTC, lorenzolewis commented on .changeset/heavy-students-exercise.md
> +Update translation string for dropdown menu label with new Starlight localization API
```suggestion
Support translated strings introduced in the Starlight 0.28 localization API
```

2024-10-04 14:35 UTC, lorenzolewis commented on packages/starlight-utils/package.json
>      "@astrojs/starlight": ">=0.16.0",
I believe it's the peer dependency that needs updated. The dev dependency is what is used while working on and developing THIS package, whereas the peer dependency lets us give a specific range for someone consuming THIS package. 

I think it's okay to leave the other change you've made here as it needed to be updated anyway 😁

2024-10-05 14:20 UTC, huijing commented on packages/starlight-utils/package.json
>      "@astrojs/starlight": ">=0.16.0",
Ok, I made the bump.

2024-10-06 19:05 UTC, lorenzolewis approved these changes

2024-10-06 19:29 UTC, lorenzolewis commented
Thanks! Just needed to change a few more things with the lock files to make it work with the site used to test.

2024-10-06 19:29 UTC, merged